[build]
  base = "projects/interactive"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED=false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

